# Generated by Django 4.1 on 2022-11-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('marks', models.IntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateApp.candidate')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.quiz')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questiontable')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempted_questions', models.IntegerField()),
                ('num_correct_questions', models.IntegerField()),
                ('num_incorrect_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateApp.candidate')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.quiz')),
            ],
        ),
    ]
