# Generated by Django 4.1 on 2022-11-09 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempted_questions', models.IntegerField(default=0, null=True)),
                ('num_correct_questions', models.IntegerField(default=0, null=True)),
                ('num_incorrect_questions', models.IntegerField(default=0, null=True)),
                ('total_marks', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateQuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, null=True)),
                ('marks', models.IntegerField(default=0, null=True)),
                ('is_attempted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidateexamquestions',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='candidateexamquestions',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='candidateexamquestions',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CandidateExam',
        ),
        migrations.DeleteModel(
            name='CandidateExamQuestions',
        ),
        migrations.AddField(
            model_name='candidatequizquestions',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidateApp.candidate'),
        ),
    ]
