# Generated by Django 4.1 on 2022-11-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_question_quizquestion_remove_questiontable_quiz_and_more'),
        ('candidateApp', '0002_candidatequiz_candidatequizquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatequizquestions',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
        migrations.AddField(
            model_name='candidatequizquestions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.quiz'),
        ),
        migrations.AddField(
            model_name='candidatequiz',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidateApp.candidate'),
        ),
        migrations.AddField(
            model_name='candidatequiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.quiz'),
        ),
    ]
