# Generated by Django 4.1 on 2022-11-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApp', '0002_candidatequiz_candidatequizquestions_and_more'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('option1', models.CharField(max_length=30, null=True)),
                ('option2', models.CharField(max_length=30, null=True)),
                ('option3', models.CharField(max_length=30, null=True)),
                ('option4', models.CharField(max_length=30, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='questiontable',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marks_per_question',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maximum_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_of_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_negative_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionTable',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.quiz'),
        ),
    ]
